[project]
name = 'Cultural-Exchange-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.entangled-pair-management]
path = 'contracts/entangled-pair-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.node-synchronization]
path = 'contracts/node-synchronization.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
